### ISSUE TITLE
Tagging Notes (#todo, #assignments etc.)

### ISSUE THREAD

**Issue by theGeekyLad** [MarcelWalk/NotesExtension#19]
_This is more of a feature request than an issue._

Been heavily using this extension since the past week for my university research; it has been super useful! I've had my friends ask me about this nifty note-taking tool they'd seen over screen share. Since then, my list of notes have grown to a prodigious number; so much so that I need to scroll on my 53cm tall screen. 😅

This essentially makes looking-up notes cumbersome. I'm not talking about a "search" feature that looks into the _content_ of notes, but a "tagging" mechanism that can _logically group_ notes without really breaking the simplicity of the extension. Not really saying the browser search `Ctrl+F` is useless but that wouldn't display a filtered subset of pertinent notes.

I've already built this for myself as I desperately needed for my college hunt and here's what it looks like:

![notes-feature](https://user-images.githubusercontent.com/15625446/137093840-4ffe3eeb-0d47-42e8-8360-4c3f863e79b7.gif)

Wondering what you, as the maintainer and developer of this project, and other users think of this inclusion?

**Comment by NyasakiAT** [comment]
I like the idea, we could use this [tag input](https://wikiki.github.io/form/tagsinput/) extensions for entering and [tags](https://bulma.io/documentation/elements/tag/) to display them.

Do you prefer the search or some kind of sidebar for it?
Kinda like this:
![image](https://user-images.githubusercontent.com/23500970/137105693-106ed6b7-bf97-480e-a242-3ecc44e900a9.png)

*Arch is a great distro btw*

**Comment by theGeekyLad** [comment]
Thanks @MarcelWalk , the Bulma tag extension seems like a great fit!

In my opinion, having the textual tags as part of the comment body translates into more free flow, as, at least in my case, something like _"for #assistanship email this prof."_ is super convenient. Now that I think of it, I'm probably a little influenced by Google Keep! :smile:

Nonetheless, having the [Bulma TagsInput](https://wikiki.github.io/form/tagsinput/) is more semantic to novice users who would otherwise not know that "#anything" would translate into a tag. While we could still combat this with a snackbar explaining the feature on first-load, it doesn't hurt just having both!

The side-bar idea actually does sounds quite nifty but I would prefer it alongside the search. The reason is, while novice users can access the feature with the mouse, pro users could simply type into the search box. It could look like a small collapse-able under the search bar; what do you think of that?

Do let me know your thoughts while try to include both in the game.

_Btw, how did you know I use Arch? :P_

**Comment by NyasakiAT** [comment]
![image](https://user-images.githubusercontent.com/23500970/137258344-0cbdc7db-b4e8-4a73-87e6-3dc81324c594.png)

Sounds reasonable, I basically just want to display the tags somewhere so the user knows which tags exist

**Comment by theGeekyLad** [comment]
Makes sense to me too. I'll get back with a PR on this. 

_Didn't notice that tab group!_
