### ISSUE TITLE
Share notes by link

### ISSUE THREAD

**Issue by Mobilpadde** [MarcelWalk/NotesExtension#4]
Would be super awesome, if you'd share notes by a link. 

A quick hack would be to create a gist with the note. Otherwise built a quick'n dirty website 🤩

**Comment by MarcelWalk** [comment]
Well I wouldänt need it but it can't hurt 

Note for me:
https://docs.github.com/en/rest/reference/gists

**Comment by MarcelWalk** [comment]
https://0x0.st/
Some text / filehosting service would be a better solution than gists since u dont need a github account
